### ISSUE TITLE
Cannot find playerId object

### ISSUE THREAD

**Issue by egaffincahn** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#38] opened 2016-09-08 20:56 UTC
Hi, I believe a commenter on the package website had a similar issue. In a call to `getProjections()`, I get the error `object 'playerId' not found`. I've stripped down my code so that all I run upon startup is:

`library("ffanalytics")`
`scrapeData <- runScrape(week = 1, season = 2016, analysts = 4, positions = c("QB"))`
`myProjections <- getProjections(scrapeData, leagueScoring = scoringRules)`

It scrapes the data successfully, but dies getting the projections during or after the `Retrieving overall ECR ranks` stage. A `playerId` variable is indeed one of the elements of the `resultData` class in my `scrapeData` list. `playerId` also exists as a character vector in `playerData`, but changing this to numeric type (as it is in my `scrapeData`) did not solve the issue. Including other input arguments for `getProjections()` did not change anything.

I'm using R 3.3.1, R Studio 0.99.903, and ffanalytics 0.1.7. Any suggestions for how to move forward would be appreciated. 

Thanks!

**Comment by williamaue** [comment] 2016-09-09 16:52
I'm suspect that I'm having the same issue. The `getProjections()` function works for me if the scraped data are for the season projections (i.e., week = 0), but the function fails at `Retrieving overall ECR ranks` when I run it on data scraped for week 1. The error code that I'm getting is:
`Error in bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch,  : 
  typeof x.player (logical) != typeof i.player (character)`

I'm running R 3.2.3, RStudio 0.99.893, and ffanalytics 0.1.8.

**Comment by egaffincahn** [comment] 2016-09-09 16:59
Yep, after updating to ffanalytics 0.1.8, I now get the same error you do.

**Comment by MrDAndersen** [comment] 2016-09-10 00:36
This should be fixed now. Please update to version 0.1.9

**Comment by egaffincahn** [comment] 2016-09-12 17:59
Thanks for the reply. I updated, and it moves past the ECR ranks fine, but now has trouble at a downstream step: The GUI that opens during `getProjections()` shows no players and upon closing, the console reads `Weekly overall rankings not available.` The `scrapeData` from `runScrape()` which I'm using for `getProjections()` does in fact have all the numeric data.

Thanks!

**Comment by je64u** [comment] 2016-09-13 22:36
I can confirm that getProjections() is not showing any players with 0.1.9 for weekly projections

**Comment by isaactpetersen** [comment] 2019-08-06 03:35
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics

**Closed by isaactpetersen** 2019-08-06 03:35 UTC
